image: openjdk:8-jdk-alpine

stages:
  - get
  - build
  - deploy

cache:
  paths:
  - build/
  - /root/.gradle/

cef.linux:
  image: openjdk:8-jdk
  stage: get
  before_script:
    - apt-get update -y && apt-get install binutils
    - chmod +x ./patchelf
  script:
    - ./gradlew copyCef -Pos=linux --no-daemon
  artifacts:
    paths:
    - com.make.cef.linux.x86_64/linux-x86_64

cef.windows:
  stage: get
  script:
    - ./gradlew copyCef -Pos=windows --no-daemon
  artifacts:
    paths:
    - com.make.cef.windows.x86_64/windows-x86_64

cef.osx:
  stage: get
  script:
    - ./gradlew copyCef -Pos=osx --no-daemon
  artifacts:
    paths:
    - com.make.cef.osx.x86_64/osx-x86_64

build.p2:
  stage: build
  script:
    - ./gradlew buildP2Repo --no-daemon
  artifacts:
    name: ${CI_JOB_NAME}_${CI_PIPELINE_ID}
    paths:
    - com.make.cef.repository/target/repository
    
build.sanpleE4:
  stage: build
  script:
    - ./gradlew buildSampleE4 --no-daemon
  artifacts:
    name: ${CI_JOB_NAME}_${CI_PIPELINE_ID}
    paths:
    - com.make.cef.sample.e4.rcp/target/products/*.zip

pages:
  image: alpine:3.5
  stage: deploy
  variables:
    GIT_STRATEGY: none
  dependencies:
  - build.p2
  script:
  - mkdir -p public
  - cp -r com.make.cef.repository/target/repository public
  after_script:
  - ls public
  - ls public/repository
  artifacts:
    paths:
    - public
    expire_in: 4 weeks
  only:
  - master
  - centos6
